export const GET_ALL_PRODUCT_SUCCESS = 'GET_ALL_PRODUCT_SUCCESS'
export const GET_ALL_PRODUCT_FAIL = 'GET_ALL_PRODUCT_FAIL'
export const GET_ALL_PRODUCT_REQUEST = 'GET_ALL_PRODUCT_REQUEST'

export const GET_PRODUCT_SLUG_SUCCESS = 'GET_PRODUCT_SLUG_SUCCESS'
export const GET_PRODUCT_SLUG_FAIL = 'GET_PRODUCT_SLUG_FAIL'
export const GET_PRODUCT_SLUG_REQUEST = 'GET_PRODUCT_SLUG_REQUEST'